services:
  bpv-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bpv-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env.production
    ports:
      - "3006:3001"
    networks:
      - unified-chat_chat-net

networks:
  unified-chat_chat-net:
    external: true
